# Generated by Django 5.1.7 on 2025-03-27 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeusermodel',
            old_name='boi',
            new_name='bio',
        ),
    ]
