# Generated by Django 5.1.7 on 2025-03-30 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_boi_customeusermodel_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeusermodel',
            name='followers',
        ),
        migrations.AddField(
            model_name='customeusermodel',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
